# Mã định danh duy nhất của dự án (Bạn có thể đặt là dolciluxe)
sonar.projectKey=dolciluxe

# Tên hiển thị trên giao diện SonarQube
sonar.projectName=Dolciluxe-Web-App

# Phiên bản của ứng dụng
sonar.projectVersion=1.0

# Thư mục cần quét (Dấu chấm là quét toàn bộ repo)
sonar.sources=.

# Bỏ qua các thư mục không cần thiết để quét nhanh hơn
sonar.exclusions=node_modules/**, dist/**, **/*.test.js

# Định dạng mã nguồn
sonar.sourceEncoding=UTF-8