output "DevOps_Node_IP" {
  description = "IP Public của máy DevOps (Jenkins)"
  value       = aws_instance.devops_node.public_ip
}

output "Master_Node_IP" {
  description = "IP Public của K3s Master Node"
  value       = aws_instance.k3s_master.public_ip
}

output "Worker_Nodes_IPs" {
  description = "Danh sách IP Public của Worker Nodes"
  value       = [for w in aws_instance.k3s_worker : w.public_ip]
}

output "Jenkins_URL" {
  description = "Link truy cập Jenkins CI/CD (chỉ mở cho admin_cidr)"
  value       = "http://${aws_instance.devops_node.public_ip}:8080"
}

output "SonarQube_URL" {
  description = "Link truy cập SonarQube (chỉ mở cho admin_cidr)"
  value       = "http://${aws_instance.devops_node.public_ip}:9000"
}

output "Ingress_Entry_Points" {
  description = "Các IP có thể dùng để truy cập Ingress (HTTP/HTTPS mở public trên master/worker)"
  value = concat(
    [aws_instance.k3s_master.public_ip],
    [for w in aws_instance.k3s_worker : w.public_ip]
  )
}

output "Command_SSH_DevOps" {
  description = "SSH nhanh vào DevOps node (private key nằm local, không commit git)"
  value       = "ssh -i ~/.ssh/vockey.pem ubuntu@${aws_instance.devops_node.public_ip}"
}

output "Command_SSH_Master" {
  description = "SSH nhanh vào K3s master"
  value       = "ssh -i ~/.ssh/vockey.pem ubuntu@${aws_instance.k3s_master.public_ip}"
}

output "Notes" {
  value = <<EOT
- inventory.ini is generated by Terraform (stage2). Do not edit it manually.
- Keep vockey.pem locally only and ensure *.pem is in .gitignore.
- Jenkins initial password output was removed because Jenkins is configured by Ansible (docker-compose + JCasC/env).
EOT
}
