variable "region" {
  type    = string
  default = "us-east-1"
}

variable "project" {
  type    = string
  default = "k3s-demo"
}

variable "env" {
  type    = string
  default = "lab"
}

# AWS Key Pair name (private key .pem is stored locally, not in git)
variable "key_name" {
  type    = string
  default = "vockey"
}

variable "devops_instance_type" {
  type    = string
  default = "t3.medium"
}

variable "k3s_instance_type" {
  type    = string
  default = "t3.small"
}

variable "worker_count" {
  type    = number
  default = 3
}



# Output inventory.ini path (generated by Terraform) - do not edit manually
variable "ansible_inventory_path" {
  type    = string
  default = "../../ansible/inventory.ini"
}

variable "ansible_user" {
  type    = string
  default = "ubuntu"
}

# Local path to private key used by Ansible/SSH (keep outside git)
variable "ansible_private_key_path" {
  type    = string
  default = "~/.ssh/vockey.pem"
}
