apiVersion: v1
kind: Service
metadata:
  name: mongo # Tên này phải khớp với cấu hình trong code Backend
spec:
  ports:
    - port: 27017
  selector:
    app: mongo
  clusterIP: None # Headless service (kết nối nội bộ)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0 # Lấy ảnh trực tiếp từ Docker Hub
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          emptyDir: {} # Lưu tạm thời (Mất dữ liệu nếu restart pod - đủ cho demo 10 ngày)