[masters] 
master ansible_host=13.220.5.216 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vockey.pem node_role=master k3s_server_ip=10.0.1.235
[workers] 
worker-0 ansible_host=44.202.227.191 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vockey.pem node_role=frontend
worker-1 ansible_host=34.205.135.76 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vockey.pem node_role=backend
worker-2 ansible_host=100.52.182.43 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vockey.pem node_role=database

[devops]
devops_node ansible_host=44.199.233.73 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vockey.pem node_role=devops

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10'
ansible_become=true
ansible_become_method=sudo
ansible_become_flags=-n
ansible_become_timeout=60
