[masters]
master ansible_host=98.92.137.148 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vockey.pem node_role=master k3s_server_ip=10.0.1.145

[workers]
worker-0 ansible_host=44.204.252.182 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vockey.pem node_role=frontend
worker-1 ansible_host=34.239.94.216 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vockey.pem node_role=backend
worker-2 ansible_host=44.214.5.45 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vockey.pem node_role=database

[devops]
devops_node ansible_host=44.211.189.20 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vockey.pem node_role=devops

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10'
ansible_become=true
ansible_become_method=sudo
ansible_become_flags=-n
ansible_become_timeout=60
